version: '3.8'
networks:
  project:
    driver: "bridge"
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - project

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    links:
      - backend
    # Mount the frontend directory, but use a volume for node_modules to ensure they are not overwritten
    restart: always
    networks:
      - project

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - project
